rb 22

diff --git a/.github/workflows/rb-tpl.yaml b/.github/workflows/rb-tpl.yaml
--- a/.github/workflows/rb-tpl.yaml
+++ b/.github/workflows/rb-tpl.yaml
@@ -43,13 +43,14 @@ jobs:
           fi
           cat $GITHUB_OUTPUT
 
-      - name: Update Docker Image Tag 🏷️
+      - name: Update Docker Image Tag �️
         run: |
           cd apps/service/overlays/${{ steps.determine_folder.outputs.folder }}
           if yq eval --exit-status '(.helmCharts[] | select(.valuesInline.name == "${{ inputs.app }}"))' kustomization.yaml > /dev/null 2>&1; then
-          yq eval -i '(.helmCharts[] | select(.valuesInline.name == "${{ inputs.app }}") | .valuesInline.image.tag) = "${{ inputs.tag }}"' kustomization.yaml
-          echo "Tag updated successfully for app: ${{ inputs.app }}""
+            yq eval -i '(.helmCharts[] | select(.valuesInline.name == "${{ inputs.app }}") | .valuesInline.image.tag) = "${{ inputs.tag }}"' kustomization.yaml
+            echo "Tag updated successfully for app: ${{ inputs.app }}"
           else
-          echo "App name not found: ${{ inputs.app }}""
+            echo "App name not found: ${{ inputs.app }}"
+            exit 1
           fi
           cat kustomization.yaml
